name 'turbs'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures turbs'
long_description 'Installs/Configures turbs'
version '0.1.0'

depends 'postgresql'
depends 'hostsfile'
depends 'apt'
depends 'database'
